# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Darwin的博客
email: mangonob@163.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

#Build settings
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers: nil

highlighter: pygments 

# style of pygments 
# $ pygmentize -f html -S friently -a .highlight > css/pygments.css
# ['manni', 'igor', 'lovelace', 'xcode', 
# 'vim', 'autumn', 'vs', 'rrt', 
# 'native', 'perldoc', 'borland', 
# 'tango', 'emacs', 'friendly', 'monokai', 
# 'paraiso-dark', 'colorful', 'murphy', 'bw', 
# 'pastie', 'algol_nu', 'paraiso-light', 'trac', 
# 'default', 'algol', 'fruity']

sass:
  sass_dir:       _sass
  style:          :expanded

# by Darwin
gems: [jekyll-paginate]
paginate: 20
paginate_path: "/page:num"

excerpt_separator: "<!--break-->"
